name: flutter_activity_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  animate_do: ^3.0.2
  flutter_riverpod: ^2.3.6

  font_awesome_flutter: ^10.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/profile.jpg
    - assets/profile.png
    - assets/proyectos/gametracker.png
    - assets/proyectos/L-MACK.png
    - assets/proyectos/sicesoft.png
